namespace ChapterTool.Avalonia.Localization;

public static class AppLocalizationResources
{
    private static readonly IReadOnlyDictionary<string, string> ZhCn = new Dictionary<string, string>(StringComparer.Ordinal)
    {
        ["App.Title"] = "[VCB-Studio] ChapterTool",
        ["Common.Apply"] = "应用",
        ["Common.Clear"] = "清空",
        ["Common.Copy"] = "复制",
        ["Common.Refresh"] = "刷新",
        ["Common.Save"] = "保存",
        ["Common.Use"] = "使用",
        ["Common.UnsupportedFeature"] = "此构建未启用该平台相关功能。",
        ["Language.ChineseSimplified"] = "简体中文",
        ["Language.English"] = "英语",
        ["Language.Japanese"] = "日语",
        ["Main.Load"] = "载入",
        ["Main.Reload"] = "重新载入",
        ["Main.AppendMpls"] = "追加合并 MPLS",
        ["Main.SaveTo"] = "选择保存目录",
        ["Main.Log"] = "日志",
        ["Main.Combine"] = "合并",
        ["Main.RoundFrames"] = "帧数取整",
        ["Main.PreviewShort"] = "预览",
        ["Main.SettingsShort"] = "设置",
        ["Main.AutoFrameRate"] = "自动",
        ["Main.Insert"] = "插入",
        ["Main.Delete"] = "删除",
        ["Main.OpenRelatedMedia"] = "打开相关媒体",
        ["Main.CreateZones"] = "生成 Zones",
        ["Main.ForwardTranslation"] = "前移帧",
        ["Main.Preview"] = "预览",
        ["Main.ColumnNumber"] = "#",
        ["Main.ColumnTime"] = "时间点",
        ["Main.ColumnName"] = "章节名",
        ["Main.ColumnFrames"] = "帧数",
        ["Main.SaveFormat"] = "保存格式",
        ["Main.ChapterName"] = "章节名",
        ["Main.KeepOriginalName"] = "保留原名",
        ["Main.StandardTemplate"] = "统一模板",
        ["Main.TemplateFile"] = "模板文件",
        ["Main.OrderShift"] = "平移章节号",
        ["Main.XmlLanguage"] = "XML语言",
        ["Main.Expression"] = "表达式",
        ["Tool.Preview.Title"] = "预览",
        ["Tool.Log.Title"] = "日志",
        ["Tool.Settings.Title"] = "设置",
        ["Tool.ColorSettings.Title"] = "颜色设置",
        ["Tool.Language.Title"] = "语言",
        ["Tool.Expression.Title"] = "表达式",
        ["Tool.TemplateNames.Title"] = "模板名称",
        ["Tool.FileAssociation.Title"] = "文件关联",
        ["Tool.Zones.Title"] = "Zones",
        ["Tool.ForwardShift.Title"] = "前移帧",
        ["Tool.ColorSlots"] = "旧版颜色槽",
        ["Tool.Expression.Placeholder"] = "表达式，例如 t + 1",
        ["Tool.Expression.Apply"] = "应用表达式",
        ["Tool.TemplateNames.UseStandard"] = "使用标准模板名称",
        ["Settings.General"] = "常规",
        ["Settings.UiLanguage"] = "界面语言",
        ["Settings.SaveDirectory"] = "默认保存目录",
        ["Settings.EmptyUsesSource"] = "留空则使用源文件目录",
        ["Settings.ExternalTools"] = "外部工具",
        ["Settings.MkvToolnixPath"] = "MKVToolNix / mkvextract",
        ["Settings.Eac3toPath"] = "eac3to",
        ["Settings.FfprobePath"] = "ffprobe",
        ["Settings.FfmpegPath"] = "FFmpeg 目录",
        ["Settings.ValidateTools"] = "检查工具",
        ["Settings.OutputDefaults"] = "输出默认值",
        ["Settings.DefaultSaveFormat"] = "默认保存格式",
        ["Settings.DefaultXmlLanguage"] = "默认 XML 语言",
        ["Settings.Appearance"] = "外观",
        ["Settings.Platform"] = "平台集成",
        ["Settings.ResetDefaults"] = "恢复默认",
        ["Settings.BrowseDirectory"] = "选择目录",
        ["Settings.BrowseExecutable"] = "选择可执行文件",
        ["Settings.Status.Ready"] = "设置已载入",
        ["Settings.Status.Saved"] = "设置已保存",
        ["Settings.Status.Reset"] = "已恢复默认值",
        ["Settings.ToolStatus.Discovery"] = "未配置，将使用 PATH 或平台发现",
        ["Settings.ToolStatus.Found"] = "已找到：{path}",
        ["Settings.ToolStatus.Missing"] = "目录中未找到 {name}",
        ["Settings.ToolStatus.InvalidPath"] = "路径不存在",
        ["Settings.ToolStatus.Unsupported"] = "当前平台不支持",
        ["Status.Ready"] = "就绪",
        ["Status.TemplateNotSelected"] = "未选择",
        ["Status.ZonesGenerated"] = "Zones 已生成",
        ["Status.NoSourceSelected"] = "未选择源文件",
        ["Status.LoadFailed"] = "载入失败",
        ["Status.LoadedChapters"] = "已载入 {count} 个章节",
        ["Status.Saved"] = "已保存",
        ["Status.SaveFailed"] = "保存失败",
        ["Status.NoCurrentMplsGroup"] = "未载入当前 MPLS 分组",
        ["Status.AppendFailed"] = "追加失败",
        ["Status.AppendedMplsSegments"] = "已追加 {count} 个 MPLS 片段",
        ["Status.Updated"] = "已更新",
        ["Status.DetectedFrameRate"] = "已检测到 {displayName}（置信度：{confidence}）",
        ["Status.ShellUnavailable"] = "Shell 服务不可用",
        ["Status.RelatedMediaNotFound"] = "未找到相关媒体文件",
        ["Status.OpenedFile"] = "已打开 {fileName}",
        ["Log.SettingsLoaded"] = "已载入设置：保存目录='{savingPath}'，语言='{language}'",
        ["Log.LanguageSet"] = "语言已设置为 {language}",
        ["Log.CreateZones"] = "生成 Zones：选中行={selectedRows}，章节数={chapters}",
        ["Log.LoadingSource"] = "正在载入源：path='{path}'",
        ["Log.StatusFromPath"] = "{status}，来源：{path}",
        ["Log.SavingChapters"] = "正在保存章节：格式={format}，目录='{directory}'，来源='{source}'，章节数={chapters}，应用表达式={applyExpression}，表达式='{expression}'",
        ["Log.SelectedSourceOption"] = "已选择源选项：index={index}，label='{label}'，source='{source}'，sourceType={sourceType}，chapters={chapters}，fps={fps}",
        ["Log.AppendingMpls"] = "正在追加 MPLS：path='{path}'",
        ["Log.EditChapters"] = "{action}：章节数 {before} -> {after}",
        ["Log.AutoFrameRateDetection"] = "自动帧率检测：option={option}，confidence={confidence}，accurate={accurate}/{evaluated}，deviation={deviation}",
        ["Log.FrameInfoUpdated"] = "帧信息已更新：option={option}，fps={fps}，round={round}，chapters={chapters}",
        ["Log.RelatedMediaNotFound"] = "{status}：reference='{reference}'，resolved='{resolved}'",
        ["Log.OpenedPath"] = "{status}：path='{path}'",
        ["Log.ImportSummary"] = "{operation} 结果：success={success}，partial={partial}，groups={groups}，options={options}，chapters={chapters}，diagnostics={diagnostics}",
        ["Log.ImportGroup"] = "{operation} 分组 {groupIndex}：sourcePath='{sourcePath}'，defaultOptionIndex={defaultOptionIndex}，options={options}",
        ["Log.ImportOption"] = "{operation} 选项 {optionIndex}：id='{id}'，label='{label}'，source='{source}'，sourceType={sourceType}，chapters={chapters}，duration={duration}，fps={fps}",
        ["Log.Diagnostic"] = "{operation} 诊断：severity={severity}，code={code}{location} message='{message}'{details}",
        ["Log.Status"] = "{status}",
        ["Prompt.FileAssociationUnsupported"] = "此构建未启用文件关联注册。"
    };

    private static readonly IReadOnlyDictionary<string, string> EnUs = new Dictionary<string, string>(StringComparer.Ordinal)
    {
        ["App.Title"] = "[VCB-Studio] ChapterTool",
        ["Common.Apply"] = "Apply",
        ["Common.Clear"] = "Clear",
        ["Common.Copy"] = "Copy",
        ["Common.Refresh"] = "Refresh",
        ["Common.Save"] = "Save",
        ["Common.Use"] = "Use",
        ["Common.UnsupportedFeature"] = "This platform-gated feature is not enabled in this build.",
        ["Language.ChineseSimplified"] = "Simplified Chinese",
        ["Language.English"] = "English",
        ["Language.Japanese"] = "Japanese",
        ["Main.Load"] = "Load",
        ["Main.Reload"] = "Reload",
        ["Main.AppendMpls"] = "Append MPLS",
        ["Main.SaveTo"] = "Choose Save Directory",
        ["Main.Log"] = "Log",
        ["Main.Combine"] = "Combine",
        ["Main.RoundFrames"] = "Round frames",
        ["Main.PreviewShort"] = "Preview",
        ["Main.SettingsShort"] = "Settings",
        ["Main.AutoFrameRate"] = "Auto",
        ["Main.Insert"] = "Insert",
        ["Main.Delete"] = "Delete",
        ["Main.OpenRelatedMedia"] = "Open Related Media",
        ["Main.CreateZones"] = "Create Zones",
        ["Main.ForwardTranslation"] = "Forward Translation",
        ["Main.Preview"] = "Preview",
        ["Main.ColumnNumber"] = "#",
        ["Main.ColumnTime"] = "Time",
        ["Main.ColumnName"] = "Name",
        ["Main.ColumnFrames"] = "Frames",
        ["Main.SaveFormat"] = "Save format",
        ["Main.ChapterName"] = "Chapter name",
        ["Main.KeepOriginalName"] = "Keep original",
        ["Main.StandardTemplate"] = "Standard template",
        ["Main.TemplateFile"] = "Template file",
        ["Main.OrderShift"] = "Order shift",
        ["Main.XmlLanguage"] = "XML language",
        ["Main.Expression"] = "Expression",
        ["Tool.Preview.Title"] = "Preview",
        ["Tool.Log.Title"] = "Log",
        ["Tool.Settings.Title"] = "Settings",
        ["Tool.ColorSettings.Title"] = "Color Settings",
        ["Tool.Language.Title"] = "Language",
        ["Tool.Expression.Title"] = "Expression",
        ["Tool.TemplateNames.Title"] = "Template Names",
        ["Tool.FileAssociation.Title"] = "File Association",
        ["Tool.Zones.Title"] = "Zones",
        ["Tool.ForwardShift.Title"] = "Forward Shift",
        ["Tool.ColorSlots"] = "Legacy color slots",
        ["Tool.Expression.Placeholder"] = "Expression, e.g. t + 1",
        ["Tool.Expression.Apply"] = "Apply expression",
        ["Tool.TemplateNames.UseStandard"] = "Use standard template names",
        ["Settings.General"] = "General",
        ["Settings.UiLanguage"] = "UI language",
        ["Settings.SaveDirectory"] = "Default save directory",
        ["Settings.EmptyUsesSource"] = "Blank uses the source directory",
        ["Settings.ExternalTools"] = "External Tools",
        ["Settings.MkvToolnixPath"] = "MKVToolNix / mkvextract",
        ["Settings.Eac3toPath"] = "eac3to",
        ["Settings.FfprobePath"] = "ffprobe",
        ["Settings.FfmpegPath"] = "FFmpeg directory",
        ["Settings.ValidateTools"] = "Check Tools",
        ["Settings.OutputDefaults"] = "Output Defaults",
        ["Settings.DefaultSaveFormat"] = "Default save format",
        ["Settings.DefaultXmlLanguage"] = "Default XML language",
        ["Settings.Appearance"] = "Appearance",
        ["Settings.Platform"] = "Platform",
        ["Settings.ResetDefaults"] = "Reset Defaults",
        ["Settings.BrowseDirectory"] = "Choose Directory",
        ["Settings.BrowseExecutable"] = "Choose Executable",
        ["Settings.Status.Ready"] = "Settings loaded",
        ["Settings.Status.Saved"] = "Settings saved",
        ["Settings.Status.Reset"] = "Defaults restored",
        ["Settings.ToolStatus.Discovery"] = "Not configured; PATH or platform discovery will be used",
        ["Settings.ToolStatus.Found"] = "Found: {path}",
        ["Settings.ToolStatus.Missing"] = "{name} was not found in this directory",
        ["Settings.ToolStatus.InvalidPath"] = "Path does not exist",
        ["Settings.ToolStatus.Unsupported"] = "Unsupported on this platform",
        ["Status.Ready"] = "Ready",
        ["Status.TemplateNotSelected"] = "Not selected",
        ["Status.ZonesGenerated"] = "Zones generated",
        ["Status.NoSourceSelected"] = "No source selected",
        ["Status.LoadFailed"] = "Load failed",
        ["Status.LoadedChapters"] = "Loaded {count} chapters",
        ["Status.Saved"] = "Saved",
        ["Status.SaveFailed"] = "Save failed",
        ["Status.NoCurrentMplsGroup"] = "No current MPLS group is loaded",
        ["Status.AppendFailed"] = "Append failed",
        ["Status.AppendedMplsSegments"] = "Appended {count} MPLS segment(s)",
        ["Status.Updated"] = "Updated",
        ["Status.DetectedFrameRate"] = "Detected {displayName} (confidence: {confidence})",
        ["Status.ShellUnavailable"] = "Shell service is unavailable",
        ["Status.RelatedMediaNotFound"] = "Related media file was not found",
        ["Status.OpenedFile"] = "Opened {fileName}",
        ["Log.SettingsLoaded"] = "Settings loaded: savingPath='{savingPath}', language='{language}'",
        ["Log.LanguageSet"] = "Language set to {language}",
        ["Log.CreateZones"] = "Create zones: selectedRows={selectedRows}, chapters={chapters}",
        ["Log.LoadingSource"] = "Loading source: path='{path}'",
        ["Log.StatusFromPath"] = "{status} from {path}",
        ["Log.SavingChapters"] = "Saving chapters: format={format}, directory='{directory}', source='{source}', chapters={chapters}, applyExpression={applyExpression}, expression='{expression}'",
        ["Log.SelectedSourceOption"] = "Selected source option: index={index}, label='{label}', source='{source}', sourceType={sourceType}, chapters={chapters}, fps={fps}",
        ["Log.AppendingMpls"] = "Appending MPLS: path='{path}'",
        ["Log.EditChapters"] = "{action}: chapters {before} -> {after}",
        ["Log.AutoFrameRateDetection"] = "Auto frame-rate detection: option={option}, confidence={confidence}, accurate={accurate}/{evaluated}, deviation={deviation}",
        ["Log.FrameInfoUpdated"] = "Frame info updated: option={option}, fps={fps}, round={round}, chapters={chapters}",
        ["Log.RelatedMediaNotFound"] = "{status}: reference='{reference}', resolved='{resolved}'",
        ["Log.OpenedPath"] = "{status}: path='{path}'",
        ["Log.ImportSummary"] = "{operation} result: success={success}, partial={partial}, groups={groups}, options={options}, chapters={chapters}, diagnostics={diagnostics}",
        ["Log.ImportGroup"] = "{operation} group {groupIndex}: sourcePath='{sourcePath}', defaultOptionIndex={defaultOptionIndex}, options={options}",
        ["Log.ImportOption"] = "{operation} option {optionIndex}: id='{id}', label='{label}', source='{source}', sourceType={sourceType}, chapters={chapters}, duration={duration}, fps={fps}",
        ["Log.Diagnostic"] = "{operation} diagnostic: severity={severity}, code={code}{location} message='{message}'{details}",
        ["Log.Status"] = "{status}",
        ["Prompt.FileAssociationUnsupported"] = "File association registration is platform-gated and not enabled in this build."
    };

    private static readonly IReadOnlyDictionary<string, string> JaJp = new Dictionary<string, string>(StringComparer.Ordinal)
    {
        ["App.Title"] = "[VCB-Studio] ChapterTool",
        ["Common.Apply"] = "適用",
        ["Common.Clear"] = "クリア",
        ["Common.Copy"] = "コピー",
        ["Common.Refresh"] = "更新",
        ["Common.Save"] = "保存",
        ["Common.Use"] = "使用",
        ["Common.UnsupportedFeature"] = "このビルドでは、このプラットフォーム依存機能は有効化されていません。",
        ["Language.ChineseSimplified"] = "簡体字中国語",
        ["Language.English"] = "英語",
        ["Language.Japanese"] = "日本語",
        ["Main.Load"] = "読み込み",
        ["Main.Reload"] = "再読み込み",
        ["Main.AppendMpls"] = "MPLS を追加結合",
        ["Main.SaveTo"] = "保存先を選択",
        ["Main.Log"] = "ログ",
        ["Main.Combine"] = "結合",
        ["Main.RoundFrames"] = "フレームを丸める",
        ["Main.PreviewShort"] = "プレビュー",
        ["Main.SettingsShort"] = "設定",
        ["Main.AutoFrameRate"] = "自動",
        ["Main.Insert"] = "挿入",
        ["Main.Delete"] = "削除",
        ["Main.OpenRelatedMedia"] = "関連メディアを開く",
        ["Main.CreateZones"] = "Zones を生成",
        ["Main.ForwardTranslation"] = "前方シフト",
        ["Main.Preview"] = "プレビュー",
        ["Main.ColumnNumber"] = "#",
        ["Main.ColumnTime"] = "時刻",
        ["Main.ColumnName"] = "チャプター名",
        ["Main.ColumnFrames"] = "フレーム",
        ["Main.SaveFormat"] = "保存形式",
        ["Main.ChapterName"] = "チャプター名",
        ["Main.KeepOriginalName"] = "元の名前を保持",
        ["Main.StandardTemplate"] = "標準テンプレート",
        ["Main.TemplateFile"] = "テンプレートファイル",
        ["Main.OrderShift"] = "番号シフト",
        ["Main.XmlLanguage"] = "XML 言語",
        ["Main.Expression"] = "式",
        ["Tool.Preview.Title"] = "プレビュー",
        ["Tool.Log.Title"] = "ログ",
        ["Tool.Settings.Title"] = "設定",
        ["Tool.ColorSettings.Title"] = "色設定",
        ["Tool.Language.Title"] = "言語",
        ["Tool.Expression.Title"] = "式",
        ["Tool.TemplateNames.Title"] = "テンプレート名",
        ["Tool.FileAssociation.Title"] = "ファイル関連付け",
        ["Tool.Zones.Title"] = "Zones",
        ["Tool.ForwardShift.Title"] = "前方シフト",
        ["Tool.ColorSlots"] = "旧形式の色スロット",
        ["Tool.Expression.Placeholder"] = "式、例: t + 1",
        ["Tool.Expression.Apply"] = "式を適用",
        ["Tool.TemplateNames.UseStandard"] = "標準テンプレート名を使用",
        ["Settings.General"] = "一般",
        ["Settings.UiLanguage"] = "UI 言語",
        ["Settings.SaveDirectory"] = "既定の保存先",
        ["Settings.EmptyUsesSource"] = "空の場合はソースの場所を使用",
        ["Settings.ExternalTools"] = "外部ツール",
        ["Settings.MkvToolnixPath"] = "MKVToolNix / mkvextract",
        ["Settings.Eac3toPath"] = "eac3to",
        ["Settings.FfprobePath"] = "ffprobe",
        ["Settings.FfmpegPath"] = "FFmpeg ディレクトリ",
        ["Settings.ValidateTools"] = "ツールを確認",
        ["Settings.OutputDefaults"] = "出力の既定値",
        ["Settings.DefaultSaveFormat"] = "既定の保存形式",
        ["Settings.DefaultXmlLanguage"] = "既定の XML 言語",
        ["Settings.Appearance"] = "外観",
        ["Settings.Platform"] = "プラットフォーム",
        ["Settings.ResetDefaults"] = "既定値に戻す",
        ["Settings.BrowseDirectory"] = "ディレクトリを選択",
        ["Settings.BrowseExecutable"] = "実行ファイルを選択",
        ["Settings.Status.Ready"] = "設定を読み込みました",
        ["Settings.Status.Saved"] = "設定を保存しました",
        ["Settings.Status.Reset"] = "既定値を復元しました",
        ["Settings.ToolStatus.Discovery"] = "未設定です。PATH またはプラットフォーム検出を使用します",
        ["Settings.ToolStatus.Found"] = "検出済み: {path}",
        ["Settings.ToolStatus.Missing"] = "このディレクトリに {name} が見つかりません",
        ["Settings.ToolStatus.InvalidPath"] = "パスが存在しません",
        ["Settings.ToolStatus.Unsupported"] = "このプラットフォームでは未対応です",
        ["Status.Ready"] = "準備完了",
        ["Status.TemplateNotSelected"] = "未選択",
        ["Status.ZonesGenerated"] = "Zones を生成しました",
        ["Status.NoSourceSelected"] = "ソースが選択されていません",
        ["Status.LoadFailed"] = "読み込みに失敗しました",
        ["Status.LoadedChapters"] = "{count} 個のチャプターを読み込みました",
        ["Status.Saved"] = "保存しました",
        ["Status.SaveFailed"] = "保存に失敗しました",
        ["Status.NoCurrentMplsGroup"] = "現在の MPLS グループが読み込まれていません",
        ["Status.AppendFailed"] = "追加に失敗しました",
        ["Status.AppendedMplsSegments"] = "{count} 個の MPLS セグメントを追加しました",
        ["Status.Updated"] = "更新しました",
        ["Status.DetectedFrameRate"] = "{displayName} を検出しました（信頼度: {confidence}）",
        ["Status.ShellUnavailable"] = "Shell サービスを利用できません",
        ["Status.RelatedMediaNotFound"] = "関連メディアファイルが見つかりません",
        ["Status.OpenedFile"] = "{fileName} を開きました",
        ["Log.SettingsLoaded"] = "設定を読み込みました: savingPath='{savingPath}', language='{language}'",
        ["Log.LanguageSet"] = "言語を {language} に設定しました",
        ["Log.CreateZones"] = "Zones 生成: selectedRows={selectedRows}, chapters={chapters}",
        ["Log.LoadingSource"] = "ソースを読み込み中: path='{path}'",
        ["Log.StatusFromPath"] = "{status}: {path}",
        ["Log.SavingChapters"] = "チャプターを保存中: format={format}, directory='{directory}', source='{source}', chapters={chapters}, applyExpression={applyExpression}, expression='{expression}'",
        ["Log.SelectedSourceOption"] = "ソースオプションを選択: index={index}, label='{label}', source='{source}', sourceType={sourceType}, chapters={chapters}, fps={fps}",
        ["Log.AppendingMpls"] = "MPLS を追加中: path='{path}'",
        ["Log.EditChapters"] = "{action}: chapters {before} -> {after}",
        ["Log.AutoFrameRateDetection"] = "自動フレームレート検出: option={option}, confidence={confidence}, accurate={accurate}/{evaluated}, deviation={deviation}",
        ["Log.FrameInfoUpdated"] = "フレーム情報を更新: option={option}, fps={fps}, round={round}, chapters={chapters}",
        ["Log.RelatedMediaNotFound"] = "{status}: reference='{reference}', resolved='{resolved}'",
        ["Log.OpenedPath"] = "{status}: path='{path}'",
        ["Log.ImportSummary"] = "{operation} result: success={success}, partial={partial}, groups={groups}, options={options}, chapters={chapters}, diagnostics={diagnostics}",
        ["Log.ImportGroup"] = "{operation} group {groupIndex}: sourcePath='{sourcePath}', defaultOptionIndex={defaultOptionIndex}, options={options}",
        ["Log.ImportOption"] = "{operation} option {optionIndex}: id='{id}', label='{label}', source='{source}', sourceType={sourceType}, chapters={chapters}, duration={duration}, fps={fps}",
        ["Log.Diagnostic"] = "{operation} diagnostic: severity={severity}, code={code}{location} message='{message}'{details}",
        ["Log.Status"] = "{status}",
        ["Prompt.FileAssociationUnsupported"] = "このビルドでは、ファイル関連付け登録は有効化されていません。"
    };

    public static IReadOnlyDictionary<string, IReadOnlyDictionary<string, string>> All { get; } =
        new Dictionary<string, IReadOnlyDictionary<string, string>>(StringComparer.OrdinalIgnoreCase)
        {
            ["zh-CN"] = ZhCn,
            ["en-US"] = EnUs,
            ["ja-JP"] = JaJp
        };

    public static IReadOnlyDictionary<string, string> Fallback => ZhCn;
}
