<?xml version="1.0" encoding="UTF-8"?>
<Playlist xmlns="http://www.dvdforum.org/2005/HDDVDVideo/Playlist" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.dvdforum.org/2005/HDDVDVideo/Playlist   file:/X:/RND/current_schemas/Playlist.xsd" displayName="Harry Potter and the Goblet of Fire HD DVD" minorVersion="0" majorVersion="1">
    <Configuration>
        <StreamingBuffer size="0" />
        <Aperture size="1920x1080" />
        <MainVideoDefaultColor color="108080" />
    </Configuration>
    <MediaAttributeList>
        <VideoAttributeItem codec="VC-1" index="1" />
        <VideoAttributeItem codec="MPEG-2" index="2" />
        <AudioAttributeItem codec="DD+" index="1" channels="6" />
        <AudioAttributeItem codec="MLP" index="2" channels="6" />
        <AudioAttributeItem codec="DD+" index="3" channels="2" />
        <SubpictureAttributeItem codec="8bitRLC" index="1" />
    </MediaAttributeList>
    <TitleSet tickBase="60fps" timeBase="60fps" defaultLanguage="en">
        <Title displayName="Feature Presentation" id="feature" titleNumber="3" titleDuration="02:37:19:18" tickBaseDivisor="4" onEnd="black">
            <PrimaryAudioVideoClip src="file:///dvddisc/HVDVD_TS/PEVOB_1.MAP" titleTimeBegin="00:00:00:00" titleTimeEnd="01:18:02:30" dataSource="Disc">
                <Video mediaAttr="1" track="1" />
                <Audio mediaAttr="1" track="1" description="English 5.1" streamNumber="1" />
                <Audio mediaAttr="2" track="2" description="English TrueHD" streamNumber="2" />
                <Audio mediaAttr="1" track="3" description="French 5.1" streamNumber="3" />
                <Audio mediaAttr="1" track="4" description="Spanish 5.1" streamNumber="4" />
            </PrimaryAudioVideoClip>
            <PrimaryAudioVideoClip src="file:///dvddisc/HVDVD_TS/PEVOB_2.MAP" titleTimeBegin="01:18:02:30" titleTimeEnd="02:36:56:04" dataSource="Disc" seamless="true">
                <Video mediaAttr="1" track="1" />
                <Audio mediaAttr="1" track="1" description="English 5.1" streamNumber="1" />
                <Audio mediaAttr="2" track="2" description="English TrueHD" streamNumber="2" />
                <Audio mediaAttr="1" track="3" description="French 5.1" streamNumber="3" />
                <Audio mediaAttr="1" track="4" description="Spanish 5.1" streamNumber="4" />
            </PrimaryAudioVideoClip>
            <PrimaryAudioVideoClip titleTimeBegin="02:36:56:04" titleTimeEnd="02:37:19:18" src="file:///dvddisc/HVDVD_TS/Interpol.MAP" dataSource="Disc" description="Interpol Warning">
                <Video track="1" />
            </PrimaryAudioVideoClip>
            <ChapterList>
                <Chapter displayName="The Riddle House" titleTimeBegin="00:00:00:00" />
                <Chapter displayName="The Portkey" titleTimeBegin="00:03:46:20" />
                <Chapter displayName="The Quidditch World Cup" titleTimeBegin="00:06:09:00" />
                <Chapter displayName="The Dark Mark" titleTimeBegin="00:09:49:30" />
                <Chapter displayName="The Triwizard Tournament" titleTimeBegin="00:13:44:30" />
                <Chapter displayName="The Goblet of Fire" titleTimeBegin="00:19:13:50" />
                <Chapter displayName="The Unforgivable Curses" titleTimeBegin="00:23:08:00" />
                <Chapter displayName="The Four Champions" titleTimeBegin="00:28:59:50" />
                <Chapter displayName="Let Events Unfold" titleTimeBegin="00:36:24:30" />
                <Chapter displayName="Rita Skeeter" titleTimeBegin="00:39:02:40" />
                <Chapter displayName="Sirius Conversation" titleTimeBegin="00:41:30:00" />
                <Chapter displayName="The Hungarian Horntail" titleTimeBegin="00:45:33:40" />
                <Chapter displayName="Transforming Malfoy" titleTimeBegin="00:49:04:50" />
                <Chapter displayName="The First Task" titleTimeBegin="00:54:03:00" />
                <Chapter displayName="Best Foot Forward" titleTimeBegin="01:02:42:50" />
                <Chapter displayName="An Unexpected Challenge" titleTimeBegin="01:09:08:50" />
                <Chapter displayName="The Yule Ball" titleTimeBegin="01:14:39:30" />
                <Chapter displayName="The Eggs Clue" titleTimeBegin="01:22:22:40" />
                <Chapter displayName="The Second Task" titleTimeBegin="01:30:29:20" />
                <Chapter displayName="Never Whole Again" titleTimeBegin="01:39:23:20" />
                <Chapter displayName="The Pensieve" titleTimeBegin="01:42:36:20" />
                <Chapter displayName="Dreams and Suspicions" titleTimeBegin="01:47:16:30" />
                <Chapter displayName="The Third Task" titleTimeBegin="01:50:12:40" />
                <Chapter displayName="Flesh Blood and Bone" titleTimeBegin="01:58:47:20" />
                <Chapter displayName="The Death Eaters" titleTimeBegin="02:01:55:00" />
                <Chapter displayName="Priori Incantatem" titleTimeBegin="02:06:29:00" />
                <Chapter displayName="Veritaserum" titleTimeBegin="02:09:53:50" />
                <Chapter displayName="Parting Ways" titleTimeBegin="02:17:29:50" />
                <Chapter displayName="End Credits" titleTimeBegin="02:23:40:00" />
            </ChapterList>
            <TrackNavigationList>
                <AudioTrack track="1" langcode="en:01" description="English 5.1" />
                <AudioTrack track="2" langcode="en:01" description="English TrueHD" />
                <AudioTrack track="3" langcode="fr:01" description="French 5.1" />
                <AudioTrack track="4" langcode="es:01" description="Spanish 5.1" />
            </TrackNavigationList>
        </Title>
    </TitleSet>
</Playlist>